Repository Team-Ampersand/GKR-Frontend, pull requests merged in 2023-11, with the labels that each got.

#47 로그아웃 기능 구현
  src/components/common/atoms/LogoutBtn/index.tsx
  src/components/common/organisms/Sidebar/index.tsx
  src/hook/useLogin.tsx
  src/utils/libs/logout.ts
  src/utils/libs/toastOption.ts
Labels: Feature

#49 Fix Router
  src/hook/useLogin.tsx
Labels: Bug

#50 제재 페이지 퍼블리싱
  src/app/allviolation/page.tsx
  src/asset/dummy/ViolationDataDummy.ts
  src/asset/svg/Minus.tsx
  src/asset/svg/index.ts
  src/components/Rule/atom/OverdueItem/index.tsx
  src/components/Rule/atom/OverdueItem/style.ts
  src/components/Rule/atom/SanctionInput/index.tsx
  src/components/Rule/atom/SanctionInput/style.ts
  src/components/Rule/molecules/OverdueList/index.tsx
  src/components/Rule/molecules/OverdueList/style.ts
  src/components/Rule/molecules/RuleHeader/index.tsx
  src/components/Rule/molecules/RuleHeader/style.ts
  src/components/Rule/molecules/SanctionBoard/index.tsx
  src/components/Rule/molecules/SanctionBoard/style.ts
  src/components/Rule/organisms/index.tsx
  src/components/Rule/organisms/style.ts
  src/components/Rule/templates/style.ts
  src/components/ViolationMenagement/atoms/ViolationItem/index.tsx
  src/components/ViolationMenagement/atoms/ViolationItem/style.ts
  src/components/ViolationMenagement/molecules/AddViolation/index.tsx
  src/components/ViolationMenagement/molecules/AddViolation/style.ts
  src/components/ViolationMenagement/molecules/ViolationList/index.tsx
  src/components/ViolationMenagement/molecules/ViolationList/style.ts
  src/components/ViolationMenagement/organisms/ViolationManagement/index.tsx
  src/components/ViolationMenagement/organisms/ViolationManagement/style.ts
  src/components/ViolationMenagement/templates/style.ts
  src/components/common/atoms/ShotInput/index.tsx
  src/components/common/atoms/ShotInput/style.ts
  src/types/components/ViolationManagement/ViolationType.ts
  src/types/components/common/ShotInputType.ts
Labels: Publishing

#53 Rename Cookie
  src/utils/apis/auth.ts
  src/utils/fetcher.ts
  src/utils/libs/apiClient.ts
  src/utils/libs/getRefresh.ts
  src/utils/libs/getToken.ts
  src/utils/libs/logout.ts
  src/utils/libs/removeToken.ts
  src/utils/libs/setToken.ts
  src/utils/libs/toastOption.ts
Labels: Bug

#55 Fetch EquipmentList
  package.json
  src/app/provider.tsx
  src/asset/data/FilterListData.ts
  src/components/common/atoms/RentalItem/index.tsx
  src/components/common/atoms/RentalItem/style.ts
  src/components/common/molecules/RentalList/index.tsx
  src/recoilAtoms/index.ts
  src/types/components/Home/EquipmentListTypes.ts
  src/types/components/common/TagsTypes.ts
  src/utils/Config/Config.json
  src/utils/apis/equipment.ts
  src/utils/libs/apiClient.ts
  src/utils/libs/requestUrls.ts
  yarn.lock
Labels: Feature

#57 Refactor requestUrl
  src/components/common/molecules/RentalList/index.tsx
  src/utils/libs/requestUrls.ts
Labels: Performance

#59 Made equipment detail fetch
  src/components/Detail/molecules/ButtonList/index.tsx
  src/components/Detail/molecules/ButtonList/style.ts
  src/components/Detail/organisms/DetailBox/index.tsx
  src/components/Home/organisms/Rental/style.ts
  src/components/Home/template/style.ts
  src/components/common/atoms/RentalItem/index.tsx
  src/components/common/atoms/RentalItem/style.ts
  src/components/common/molecules/RentalList/index.tsx
  src/recoilAtoms/index.ts
  src/types/components/Detail/ButtonListType.ts
  src/utils/apis/equipment.ts
  src/utils/libs/requestUrls.ts
Labels: Feature

#64 Update auth
  src/components/Promotion/organisms/index.tsx
  src/hook/useFetch.tsx
  src/hook/useLogin.tsx
  src/utils/apis/auth.ts
Labels: Refactor

#66 제재내역 스타일 수정 및 데이터 작업
  src/components/Violation/atom/Item/ViolationItem/style.ts
  src/components/Violation/molecules/Box/VoilationList/index.tsx
  src/components/ViolationMenagement/atoms/ViolationItem/index.tsx
  src/components/ViolationMenagement/atoms/ViolationItem/style.ts
  src/components/ViolationMenagement/molecules/AddViolation/index.tsx
  src/components/ViolationMenagement/molecules/ViolationList/index.tsx
  src/recoilAtoms/index.ts
  src/utils/apis/data.ts
  src/utils/libs/requestUrls.ts
Labels: Publishing

#71 Admin 대여 목록 기능구현
  src/components/Detail/organisms/DetailBox/index.tsx
  src/components/Rental/atoms/RentalItem/index.tsx
  src/components/Rental/atoms/RentalItem/style.ts
  src/components/Rental/molecules/NoReturnList/index.tsx
  src/components/Rental/molecules/RentalList/index.tsx
  src/components/Rental/molecules/RentingList/index.tsx
  src/types/components/Rental/RentalType.ts
  src/utils/libs/requestUrls.ts
Labels: Feature

#72 제재사항 로직 변경
  src/app/allviolation/page.tsx
  src/components/ViolationMenagement/atoms/ViolationItem/index.tsx
  src/components/ViolationMenagement/molecules/AddViolation/index.tsx
  src/components/ViolationMenagement/molecules/ViolationList/index.tsx
  src/components/ViolationMenagement/organisms/ViolationManagement/index.tsx
  src/types/components/ViolationManagement/ViolationType.ts
  src/utils/apis/data.ts
  src/utils/libs/requestUrls.ts
Labels: Refactor

#76 삭제 기능 구현
  src/asset/svg/Caution.tsx
  src/components/Product/atom/Item/DeleteBtn/index.tsx
  src/components/Product/atom/modal/DeleteModal/index.tsx
  src/components/Product/molecules/Box/DeleteBox/index.tsx
  src/components/Product/organisms/index.tsx
  src/components/Product/organisms/style.ts
  src/components/ViolationMenagement/molecules/AddViolation/index.tsx
  src/components/common/molecules/RentalList/index.tsx
  src/components/common/molecules/RentalList/style.ts
  src/types/components/Home/FilterTypes.ts
  src/utils/apis/data.ts
  src/utils/libs/requestUrls.ts
Labels: Feature

#74 user정보 띄우기
  src/app/rentallist/admin/page.tsx
  src/app/rentallist/page.tsx
  src/components/Rental/molecules/UserRentalList/index.tsx
  src/components/Rental/molecules/UserRentalList/style.ts
  src/components/Rental/organisms/AdminRental/index.tsx
  src/components/Rental/organisms/AdminRental/style.ts
  src/components/Rental/organisms/UserRental/index.tsx
  src/components/Rental/organisms/UserRental/style.ts
  src/components/ViolationMenagement/molecules/ViolationList/index.tsx
  src/components/common/molecules/ProfileBoard/index.tsx
  src/utils/apis/data.ts
  src/utils/apis/user.ts
  src/utils/libs/requestUrls.ts
Labels: Feature

#79 Order API 작업
  src/app/rentallist/page.tsx
  src/asset/data/MenuData.ts
  src/components/Detail/molecules/ButtonList/index.tsx
  src/components/Detail/molecules/ButtonList/style.ts
  src/components/Detail/organisms/DetailBox/index.tsx
  src/components/Home/atoms/Modal/FilterModal/index.tsx
  src/components/Rental/molecules/RentalList/index.tsx
  src/components/Rental/molecules/RequestList/index.tsx
  src/components/Rental/molecules/RequestList/style.ts
  src/components/Rental/molecules/UserRentalList/index.tsx
  src/components/Rental/organisms/AdminRental/index.tsx
  src/components/Rental/organisms/UserRental/index.tsx
  src/components/Request/atoms/RequestItem/index.tsx
  src/components/Request/atoms/RequestItem/style.ts
  src/components/Request/molecules/RequestButtonList/index.tsx
  src/components/Request/molecules/RequestList/index.tsx
  src/components/Request/organisms/RequestDetail/index.tsx
  src/components/ViolationMenagement/atoms/ViolationItem/index.tsx
  src/components/common/atoms/ChoiceItem/index.tsx
  src/components/common/atoms/ChoiceItem/style.ts
  src/components/common/atoms/RentalItem/index.tsx
  src/components/common/molecules/RentalList/index.tsx
  src/types/components/Detail/ButtonListType.ts
  src/types/components/Home/RentalTypes.ts
  src/types/components/Rental/RentalType.ts
  src/types/components/Request/RequestDetailType.ts
  src/utils/apis/data.ts
  src/utils/libs/requestUrls.ts
Labels: Feature, Publishing

#81 order 요청 마무리
  src/components/Detail/molecules/ButtonList/index.tsx
  src/components/Detail/organisms/DetailBox/index.tsx
  src/recoilAtoms/index.ts
  src/types/components/Detail/ButtonListType.ts
  src/utils/libs/requestUrls.ts
Labels: Refactor

#85 기자재 수정 로직 추가
  src/app/home/[detail]/edit/page.tsx
  src/components/Detail/organisms/DetailBox/index.tsx
  src/components/Detail/organisms/DetailEdit/inex.tsx
  src/components/Detail/organisms/DetailEdit/style.ts
  src/components/Product/molecules/AddEquipment/index.tsx
  src/components/common/ImgBox/index.tsx
  src/components/common/ImgBox/style.ts
  src/components/common/atoms/InputItem/index.tsx
  src/components/common/atoms/InputItem/style.ts
  src/recoilAtoms/index.ts
  src/utils/apis/data.ts
  src/utils/libs/requestUrls.ts
Labels: Feature

#87 공지사항 수정 구현
  src/components/NoticeManagement/atoms/NoticeManagementItem/index.tsx
  src/components/NoticeManagement/molecules/EditNotice/index.tsx
  src/components/NoticeManagement/molecules/EditNotice/style.ts
  src/components/NoticeManagement/organisms/NoticeManagement/index.tsx
  src/recoilAtoms/index.ts
  src/utils/libs/requestUrls.ts
Labels: Feature, Publishing

#89 기자재 상세 기능추가
  src/components/Detail/molecules/ButtonList/index.tsx
  src/components/Detail/molecules/ReasonModal/index.tsx
  src/components/Detail/molecules/ReasonModal/style.ts
  src/components/Detail/organisms/DetailBox/index.tsx
  src/recoilAtoms/index.ts
  src/types/components/Detail/ButtonListType.ts
  src/utils/libs/requestUrls.ts
Labels: Feature
