Repository Team-Ampersand/GKR-Frontend, pull requests merged in 2023-10, with the labels that each got.

#28 물품 등록 페이지 퍼블리싱
  src/app/productmanagement/page.tsx
  src/app/regist/page.tsx
  src/app/request/[id]/page.tsx
  src/asset/data/MenuData.ts
  src/asset/svg/Camera.tsx
  src/asset/svg/Caution.tsx
  src/asset/svg/index.ts
  src/components/Product/atom/ChoiceItem/index.tsx
  src/components/Product/atom/ChoiceItem/style.ts
  src/components/Product/atom/InputItem/index.tsx
  src/components/Product/atom/InputItem/style.ts
  src/components/Product/atom/ListItem/index.tsx
  src/components/Product/atom/ListItem/style.ts
  src/components/Product/molecules/ ImgBox/index.tsx
  src/components/Product/molecules/ ImgBox/style.ts
  src/components/Product/molecules/ChoiceBox/index.tsx
  src/components/Product/molecules/ChoiceBox/style.ts
  src/components/Product/molecules/InputBox/index.tsx
  src/components/Product/molecules/InputBox/style.ts
  src/components/Product/molecules/ListBox/index.tsx
  src/components/Product/molecules/ListBox/style.ts
  src/components/Product/organisms/index.tsx
  src/components/Product/organisms/style.ts
  src/components/Product/templates/style.ts
  src/components/Regist/atom/InputItem/style.ts
  src/components/Regist/molecules/BannerBox/index.tsx
  src/components/Regist/molecules/BannerBox/style.ts
  src/components/Regist/molecules/InputBox/index.tsx
  src/components/Regist/molecules/InputBox/style.ts
  src/components/Regist/organisms/index.tsx
  src/components/Regist/organisms/style.ts
  src/components/common/atoms/Button/index.tsx
  src/components/common/atoms/Button/style.ts
  src/recoilAtoms/index.ts
Labels: Refactor, Publishing

#29 메인 페이지 퍼블리싱
  .gitignore
  src/app/home/page.tsx
  src/asset/data/FilterListData.ts
  src/asset/dummy/RentalListdummy.ts
  src/asset/svg/Filter.tsx
  src/asset/svg/index.ts
  src/components/Home/atoms/Button/FilterButton/index.tsx
  src/components/Home/atoms/Button/FilterButton/style.ts
  src/components/Home/atoms/Button/MenuButton/index.tsx
  src/components/Home/atoms/Button/MenuButton/style.ts
  src/components/Home/atoms/Items/FIlterItem/index.tsx
  src/components/Home/atoms/Items/FIlterItem/style.ts
  src/components/Home/atoms/Items/RentalItem/index.tsx
  src/components/Home/atoms/Items/RentalItem/style.ts
  src/components/Home/atoms/Modal/FilterModal/index.tsx
  src/components/Home/atoms/Modal/FilterModal/style.ts
  src/components/Home/molecules/Filter/index.tsx
  src/components/Home/molecules/Filter/style.ts
  src/components/Home/molecules/MenuList/index.tsx
  src/components/Home/molecules/MenuList/style.ts
  src/components/Home/molecules/RentalItem/index.tsx
  src/components/Home/molecules/RentalItem/style.ts
  src/components/Home/molecules/RentalList/index.tsx
  src/components/Home/molecules/RentalList/style.ts
  src/components/Home/organisms/Rental/index.tsx
  src/components/Home/organisms/Rental/style.ts
  src/components/Home/organisms/RentalList/index.tsx
  src/components/common/atoms/Tag/index.tsx
  src/components/common/atoms/Tag/style.ts
  src/components/common/molecules/SearchField/style.ts
  src/recoilAtoms/index.ts
  src/types/components/Home/FilterTypes.ts
  src/types/components/Home/RentalTypes.ts
  src/types/components/common/TagsTypes.ts
Labels: Refactor, Publishing

#34 리뷰어 수정
  .github/CODEOWNERS
Labels: Setting

#36 제재내역 페이지 퍼블리싱
  src/app/rentallist/page.tsx
  src/app/violation/page.tsx
  src/components/Product/molecules/Box/ChoiceBox/index.tsx
  src/components/Product/molecules/Box/ChoiceBox/style.ts
  src/components/Product/molecules/Box/DeleteBox/index.tsx
  src/components/Product/molecules/Box/DeleteBox/style.ts
  src/components/Product/molecules/Box/ImgBox/index.tsx
  src/components/Product/molecules/Box/ImgBox/style.ts
  src/components/Product/molecules/Box/InputBox/index.tsx
  src/components/Product/molecules/Box/InputBox/style.ts
  src/components/Product/molecules/Box/ListBox/index.tsx
  src/components/Product/molecules/Box/ListBox/style.ts
  src/components/Product/organisms/index.tsx
  src/components/Product/organisms/style.ts
  src/components/Violation/atom/Item/ViolationItem/index.tsx
  src/components/Violation/atom/Item/ViolationItem/style.ts
  src/components/Violation/molecules/Box/TopBox/index.tsx
  src/components/Violation/molecules/Box/TopBox/style.ts
  src/components/Violation/molecules/Box/VoilationListBox/index.tsx
  src/components/Violation/molecules/Box/VoilationListBox/style.ts
  src/components/Violation/organisms/index.tsx
  src/components/Violation/organisms/style.ts
  src/components/Violation/templates/style.ts
  src/recoilAtoms/index.ts
Labels: Publishing
