Repository Team-Ampersand/GKR-Frontend, pull requests merged in 2023-09, with the labels that each got.

#19 [#17] sidebar url이슈
  src/components/common/molecules/SidebarList/index.tsx
Labels: Refactor

#21 [#20] 요청내역 페이지 퍼블리싱
  src/app/request/[id]/page.tsx
  src/app/request/page.tsx
  src/components/Request/atom/RequestItem/index.tsx
  src/components/Request/atom/RequestItem/style.ts
  src/components/Request/molecules/RequestList/index.tsx
  src/components/Request/molecules/RequestList/style.ts
  src/components/Request/organisms/Request/index.tsx
  src/components/Request/organisms/Request/style.ts
  src/components/Request/organisms/RequestDetail/index.tsx
  src/components/Request/organisms/RequestDetail/style.ts
  src/components/common/atoms/Button/index.tsx
  src/components/common/atoms/Button/style.ts
  src/components/common/molecules/ProfileBoard/style.ts
Labels: Publishing

#24 [#22] CODEOWNERS 수정
  .github/CODEOWNERS
  package.json
  src/app/home/[detail]/page.tsx
  src/asset/svg/Calendar.svg
  src/asset/svg/index.ts
  src/components/Detail/molecules/InputField/index.tsx
  src/components/Detail/molecules/InputField/style.ts
  src/components/Detail/organisms/RentalForm/index.tsx
  src/components/Detail/organisms/RentalForm/style.ts
  src/components/Detail/templates/style.ts
  src/components/common/atoms/Calendar/index.tsx
  src/components/common/atoms/Calendar/style.ts
  src/recoilAtoms/index.ts
  yarn.lock
Labels: Docs

#25 [#23] Custom Scrollbar 만들기
  src/components/common/atoms/Scrollbar/style.ts
Labels: Publishing
